/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Addmission;

import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import message.MessagePane;
/**
 *
 * @author Moin
 */
public final class Admission extends javax.swing.JFrame{

    /**
     * Creates new form Admission
     */
    //create instance variable for database connection
     Connection con;
     Statement stmt;
     ResultSet rs;
     PreparedStatement pr;
     //instance variable for mouse drag
     int xMouse;
     int yMouse;
     
   
    public Admission(){
        initComponents();
        connect();
        id();
        radio();
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/login/img/icon.png")));
       
    }
    
    //this radio method create for radio button select any one radio button
    public void radio(){
     ButtonGroup bn = new ButtonGroup();
     bn.add(jRadioButton1);
     bn.add(jRadioButton2);
    }
   
    //this method create for datebase connection.
    public void connect(){
      
        String uHost="jdbc:derby://localhost:1527/School Management";
        String uName="moin";
        String uPass="akhtar";
        try {//make an connection
             con = DriverManager.getConnection(uHost, uName, uPass);
             stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
             //create statment query
             String sql = "Select * from MOIN.ADMISSION";
             rs = stmt.executeQuery(sql);
         } catch (SQLException ex) {
             error.Error er = new error.Error();
             er.displayPane("Start NeatBeans Server");
             
         }finally{
        try{}
        catch(Exception e){
             
         }
        }
    
    }
    
    //this method id get id from databse and set id when program is running
    public void id(){
         try {
             rs.last();
             String id = rs.getString("ID");
             jLabel4.setText(id);
         } catch (SQLException ex) {
           
         }finally{
        try{ rs.close(); pr.close();}
        catch(Exception e){
         }
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textID = new javax.swing.JLabel();
        textNAME = new javax.swing.JLabel();
        text_Fname = new javax.swing.JLabel();
        textEmail = new javax.swing.JLabel();
        textNum = new javax.swing.JLabel();
        textNum1 = new javax.swing.JLabel();
        textIDD = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        textF_Name = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        textTelephone = new javax.swing.JTextField();
        textEMAIL = new javax.swing.JTextField();
        textNum2 = new javax.swing.JLabel();
        textNum3 = new javax.swing.JLabel();
        textCountry = new javax.swing.JTextField();
        textNum4 = new javax.swing.JLabel();
        textCITY = new javax.swing.JTextField();
        textNum5 = new javax.swing.JLabel();
        jComboMonth = new javax.swing.JComboBox<>();
        jComboYear = new javax.swing.JComboBox<>();
        jComboDate = new javax.swing.JComboBox<>();
        textNum6 = new javax.swing.JLabel();
        textOCCUPATION = new javax.swing.JTextField();
        textNum7 = new javax.swing.JLabel();
        textCELL_NO = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNum8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboClass = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textAmount = new javax.swing.JTextField();
        textNum9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jmini = new javax.swing.JLabel();
        jclose = new javax.swing.JLabel();
        framedrag = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admission Form");
        setLocation(new java.awt.Point(250, 50));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(755, 676));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        textID.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(204, 0, 51));
        textID.setText("ID");

        textNAME.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNAME.setText("Name:");

        text_Fname.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        text_Fname.setText("Father Name:");

        textEmail.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textEmail.setText("Email:");

        textNum.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum.setText("Cell No#");

        textNum1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum1.setText("Address:");

        textIDD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textIDD.setAlignmentX(1.5F);
        textIDD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        textIDD.setName("Name");
        textIDD.setSelectionColor(new java.awt.Color(0, 204, 255));
        textIDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDDActionPerformed(evt);
            }
        });
        textIDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIDDKeyTyped(evt);
            }
        });

        textName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textName.setName("Name");
        textName.setSelectionColor(new java.awt.Color(0, 204, 255));
        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        textF_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textF_Name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textF_Name.setName("Name");
        textF_Name.setSelectionColor(new java.awt.Color(0, 204, 255));
        textF_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_NameActionPerformed(evt);
            }
        });

        textAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textAddress.setName("Name");
        textAddress.setSelectionColor(new java.awt.Color(0, 204, 255));
        textAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddressActionPerformed(evt);
            }
        });
        textAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAddressKeyTyped(evt);
            }
        });

        textTelephone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTelephone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textTelephone.setName("Name");
        textTelephone.setSelectionColor(new java.awt.Color(0, 204, 255));
        textTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelephoneActionPerformed(evt);
            }
        });
        textTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelephoneKeyTyped(evt);
            }
        });

        textEMAIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textEMAIL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textEMAIL.setName("Name");
        textEMAIL.setSelectionColor(new java.awt.Color(0, 204, 255));
        textEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEMAILActionPerformed(evt);
            }
        });

        textNum2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum2.setText("Class:");

        textNum3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum3.setText("Country:");

        textCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCountry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCountry.setName("Name");
        textCountry.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCountryActionPerformed(evt);
            }
        });
        textCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCountryKeyTyped(evt);
            }
        });

        textNum4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum4.setText("City");

        textCITY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCITY.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCITY.setName("Name");
        textCITY.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCITYActionPerformed(evt);
            }
        });
        textCITY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCITYKeyTyped(evt);
            }
        });

        textNum5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum5.setText("Date of Birth:");

        jComboMonth.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboMonth.setForeground(new java.awt.Color(255, 0, 51));
        jComboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUG", "SEPT", "OCT", "NOV", "DEC" }));

        jComboYear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboYear.setForeground(new java.awt.Color(255, 0, 51));
        jComboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2015", "2016", "2017", "2018" }));

        jComboDate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboDate.setForeground(new java.awt.Color(255, 0, 51));
        jComboDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDateActionPerformed(evt);
            }
        });

        textNum6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum6.setText("Occupation:");

        textOCCUPATION.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textOCCUPATION.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textOCCUPATION.setName("Name");
        textOCCUPATION.setSelectionColor(new java.awt.Color(0, 204, 255));
        textOCCUPATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOCCUPATIONActionPerformed(evt);
            }
        });
        textOCCUPATION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textOCCUPATIONKeyTyped(evt);
            }
        });

        textNum7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum7.setText("Tel No#");

        textCELL_NO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCELL_NO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCELL_NO.setName("Name");
        textCELL_NO.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCELL_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCELL_NOActionPerformed(evt);
            }
        });
        textCELL_NO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCELL_NOKeyTyped(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox1.setText("I Accept all Terms & Condition");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/Print_24x24.png"))); // NOI18N
        jButton3.setText("Save & Print Form");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Entered ID");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("1");

        textNum8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum8.setText("Gender:");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton1.setText("Male");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 255));
        jRadioButton2.setText("Female");

        jComboClass.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboClass.setForeground(new java.awt.Color(255, 0, 51));
        jComboClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Montssori", "Nursery", "KG", "KG1", "KG2", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X" }));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/webcam.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/Upload to the Cloud.png"))); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        textAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textAmount.setName("Name");
        textAmount.setSelectionColor(new java.awt.Color(0, 204, 255));
        textAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAmountActionPerformed(evt);
            }
        });
        textAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAmountKeyTyped(evt);
            }
        });

        textNum9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum9.setText("Admission Amount");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textID)
                                    .addComponent(textNAME)
                                    .addComponent(text_Fname)
                                    .addComponent(textEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textEMAIL)
                                    .addComponent(textName)
                                    .addComponent(textF_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(textIDD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNum1)
                                    .addComponent(textNum7)
                                    .addComponent(textNum2))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(textNum3)
                                        .addGap(18, 18, 18)
                                        .addComponent(textCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(textNum4)
                                        .addGap(18, 18, 18)
                                        .addComponent(textCITY))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(textNum)
                                        .addGap(18, 18, 18)
                                        .addComponent(textCELL_NO))
                                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(textNum5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(textNum8)
                                        .addGap(47, 47, 47)
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textNum9)
                                    .addComponent(textNum6))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAmount)
                                    .addComponent(textOCCUPATION)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textID)
                                .addGap(18, 18, 18)
                                .addComponent(textNAME)
                                .addGap(18, 18, 18)
                                .addComponent(text_Fname))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textIDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmail)
                            .addComponent(textEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(textNum7))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNum)
                        .addComponent(textCELL_NO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNum1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum2)
                    .addComponent(textNum3)
                    .addComponent(textCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNum4)
                    .addComponent(textCITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum5)
                    .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNum6)
                    .addComponent(textOCCUPATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textNum9)
                        .addComponent(textAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textNum8)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)))
                .addGap(3, 3, 3)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("ADMISSION FORM");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/school3.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Karachi Secondary School");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel8)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 750, 610));

        jLabel23.setFont(new java.awt.Font("Traditional Arabic", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("+256704277679");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Contact#");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, -1, -1));

        jLabel21.setFont(new java.awt.Font("Traditional Arabic", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CoreTechTechnologies");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 655, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Develop By");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 655, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/bnewadd.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 755, -1));

        jmini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/mini.png"))); // NOI18N
        jmini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jminiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jminiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jminiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jminiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jminiMouseReleased(evt);
            }
        });
        getContentPane().add(jmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 6, 24, 26));

        jclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/close.png"))); // NOI18N
        jclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcloseMouseReleased(evt);
            }
        });
        getContentPane().add(jclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 6, 26, 26));

        framedrag.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        framedrag.setForeground(new java.awt.Color(255, 255, 255));
        framedrag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        framedrag.setText("<html>\n<span style=\"text-shadow: 0 1px 0 #ccc,\n               0 2px 0 #c9c9c9,\n               0 3px 0 #bbb,\n               0 4px 0 #b9b9b9,\n               0 5px 0 #aaa,\n               0 6px 1px rgba(0,0,0,.1),\n               0 0 5px rgba(0,0,0,.1),\n               0 1px 3px rgba(0,0,0,.3),\n               0 3px 5px rgba(0,0,0,.2),\n               0 5px 10px rgba(0,0,0,.25),\n               0 10px 10px rgba(0,0,0,.2),\n               0 20px 20px rgba(0,0,0,.15); box-shadow:red 2px 2px \">\nNew Admission\n</span>\n<html>");
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        getContentPane().add(framedrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 22));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/tnewadd.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 35));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/bc.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 676));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDDActionPerformed
       
    }//GEN-LAST:event_textIDDActionPerformed

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void textF_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textF_NameActionPerformed

    private void textEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEMAILActionPerformed

    private void textTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelephoneActionPerformed

    }//GEN-LAST:event_textTelephoneActionPerformed

    private void textTelephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelephoneKeyTyped
        //i am using char datatype for get getkeychar from textfield and creating an if statement
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textTelephoneKeyTyped

    private void textIDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIDDKeyTyped
        //i am using char datatype for get getkeychar from textfield and creating an if statement
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textIDDKeyTyped

    private void textAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressActionPerformed

    private void textAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressKeyTyped

    private void textCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCountryActionPerformed

    private void textCountryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCountryKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textCountryKeyTyped

    private void textCITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCITYActionPerformed

    private void textCITYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCITYKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textCITYKeyTyped

    private void jComboDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboDateActionPerformed

    private void textOCCUPATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOCCUPATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textOCCUPATIONActionPerformed

    private void textOCCUPATIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textOCCUPATIONKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textOCCUPATIONKeyTyped

    private void textCELL_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCELL_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCELL_NOActionPerformed

    private void textCELL_NOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCELL_NOKeyTyped
         //i am using char datatype for get getkeychar from textfield and creating an if statement
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textCELL_NOKeyTyped
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JFileChooser  chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        file_name = f.getAbsolutePath();
        try {
            File img = new File(file_name);
            FileInputStream file = new FileInputStream(img);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            
            for(int read; (read=file.read(buf))!=-1;){
                bos.write(buf,0,read);
                
            }
            perImg = bos.toByteArray();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admission.class.getName()).log(Level.SEVERE, null, ex);
        }
        byte[] bt = perImg;
        ImageIcon ii = new ImageIcon(bt);
        jLabel2.setIcon(ii);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //this if statment for select checkbox and img then it will be invoke
        if(jCheckBox1.isSelected() && (format != null || perImg != null  )){
           String id = textIDD.getText();
           String name = textName.getText();
           String f_Name = textF_Name.getText();
           String email = textEMAIL.getText();
           String tele = textTelephone.getText();
           String cell = textCELL_NO.getText();
           String address = textAddress.getText();
           String clas = (String) jComboClass.getSelectedItem();
           String country = textCountry.getText();
           String city = textCITY.getText();
           String Date_of_birth = (String) jComboDate.getSelectedItem() + jComboMonth.getSelectedItem() + jComboYear.getSelectedItem();
           String occu = textOCCUPATION.getText();
           String amount =  textAmount.getText();
           String rd = "";
        if(jRadioButton1.isSelected()){
            rd = jRadioButton1.getText();
        }
        else if(jRadioButton2.isSelected()){
            rd = jRadioButton2.getText();
        }           
            try {
                //create query for prepareStatement for insert data into database
                String sqq = "insert into MOIN.ADMISSION (ID,NAME,F_NAME,EMAIL,TELEPHONE,CELL_NO,ADDRESS,CLASS,COUNTRY,CITY,DATE_OF_BIRTH,OCCUPATION,ADDMISSION_DATE,PHOTO,GENDER,AMOUNT) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                pr = con.prepareStatement(sqq);
                pr.setInt(1,Integer.parseInt(id));
                pr.setString(2, name);
                pr.setString(3, f_Name);
                pr.setString(4, email);
                pr.setString(5, tele);
                pr.setString(6, cell);
                pr.setString(7, address);
                pr.setString(8, clas);
                pr.setString(9, country);
                pr.setString(10, city);
                pr.setString(11, Date_of_birth);
                pr.setString(12, occu);
                pr.setDate(13,Date.valueOf(LocalDate.now()));
                pr.setBytes(14, perImg);
                pr.setString(15, rd);
                pr.setString(16, amount);
                pr.execute();
                pr.close();
                rs.close();
                //this query insert data in fees database
                String sq = "insert into MOIN.FEES (ID,NAME,CLASS) values(?,?,?)";
                pr = con.prepareStatement(sq);
                pr.setInt(1,Integer.parseInt(id));
                pr.setString(2, name);
                pr.setString(3, clas);
                pr.execute();
                pr.close();
                rs.close();
                //this query insert data in feesincome
                String sqqq = "insert into MOIN.ADMIN (FEESINCOME) values(?)";
                pr = con.prepareStatement(sqqq);
                pr.setInt(1,Integer.parseInt(amount));
                pr.execute();
                pr.close();
                rs.close();
             
                MessagePane ms = new MessagePane();
                ms.displayPane("Successfully Admission");
                textIDD.setText(null);
                textName.setText(null);
                textF_Name.setText(null);
                textEMAIL.setText(null);
                textTelephone.setText(null);
                textCELL_NO.setText(null);
                textAddress.setText(null);
                textCountry.setText(null);
                textCITY.setText(null);
                jComboClass.setSelectedIndex(0);
                textOCCUPATION.setText(null);
                String sql = "Select * from MOIN.ADMISSION";
                rs = stmt.executeQuery(sql);
                rs.last();
                String idd = rs.getString("ID");
                jLabel4.setText(idd);
                rs.close(); pr.close();
                this.dispose();
                //create an object for print out slip
             slip ads = new slip();
             ads.setVisible(true);
             
                
            } catch (SQLException | HeadlessException ex) {
                error.Error er = new error.Error();
                er.displayPane("<html><font size=\"1.5\">Please use unique ID or Cell or Address</font></html>");
        }finally{
        try{}
        catch(Exception e){
           
         }
        }
           
        }
        else{
            error.Error er = new error.Error();
            er.displayPane("<html><font size=\"1.5\">Please Accept term & Condition OR Upload Photo</font></html>");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAmountActionPerformed

    private void textAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAmountKeyTyped
          //i am using char datatype for get getkeychar from textfield and creating an if statement 
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textAmountKeyTyped

    private void jminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseClicked
        // this is use for minimize
        this.setState(Admission.ICONIFIED);

    }//GEN-LAST:event_jminiMouseClicked

    private void jminiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseEntered
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/minihover.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseEntered

    private void jminiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseExited
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/mini.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseExited

    private void jminiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMousePressed
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/miniclick.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMousePressed

    private void jminiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseReleased
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/minihover.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseReleased

    private void jcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseClicked
        // close jframe
        this.dispose();

    }//GEN-LAST:event_jcloseMouseClicked

    private void jcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseEntered
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closehover.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseEntered

    private void jcloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseExited
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/close.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseExited

    private void jcloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMousePressed
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closeclick.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMousePressed

    private void jcloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseReleased
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closehover.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseReleased

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        //set screen
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y - yMouse);

    }//GEN-LAST:event_framedragMouseDragged

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
        //set mouse pressed screen
        xMouse  = evt.getX();
        yMouse  = evt.getY();
    }//GEN-LAST:event_framedragMousePressed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel framedrag;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboClass;
    private javax.swing.JComboBox<String> jComboDate;
    private javax.swing.JComboBox<String> jComboMonth;
    private javax.swing.JComboBox<String> jComboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel jclose;
    private javax.swing.JLabel jmini;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textAmount;
    private javax.swing.JTextField textCELL_NO;
    private javax.swing.JTextField textCITY;
    private javax.swing.JTextField textCountry;
    private javax.swing.JTextField textEMAIL;
    private javax.swing.JLabel textEmail;
    private javax.swing.JTextField textF_Name;
    private javax.swing.JLabel textID;
    private javax.swing.JTextField textIDD;
    private javax.swing.JLabel textNAME;
    private javax.swing.JTextField textName;
    private javax.swing.JLabel textNum;
    private javax.swing.JLabel textNum1;
    private javax.swing.JLabel textNum2;
    private javax.swing.JLabel textNum3;
    private javax.swing.JLabel textNum4;
    private javax.swing.JLabel textNum5;
    private javax.swing.JLabel textNum6;
    private javax.swing.JLabel textNum7;
    private javax.swing.JLabel textNum8;
    private javax.swing.JLabel textNum9;
    private javax.swing.JTextField textOCCUPATION;
    private javax.swing.JTextField textTelephone;
    private javax.swing.JLabel text_Fname;
    // End of variables declaration//GEN-END:variables

//this globale variable or instance variable
String file_name = null;
private  ImageIcon format  = null;
int s = 0;
byte[] perImg = null;

   
}
