/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Addmission;

import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import message.MessagePane;
/**
 *
 * @author Moin
 */
public final class update extends javax.swing.JFrame{

    /**
     * Creates new form Admission
     */
    //create instance variable for database connection
     Connection con;
     Statement stmt;
     ResultSet rs;
     PreparedStatement pr;
     //instance variable for mouse drag
     int xMouse;
     int yMouse;
     
   
    public update(){
        initComponents();
        connect();
        id();
        
        this.setLocationRelativeTo(this);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/login/img/icon.png")));
       
    }
    
    
   
    //this method create for datebase connection.
    public void connect(){
      
        String uHost="jdbc:derby://localhost:1527/School Management";
        String uName="moin";
        String uPass="akhtar";
        try {//make an connection
             con = DriverManager.getConnection(uHost, uName, uPass);
             stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
             //create statment query
             String sql = "Select * from MOIN.ADMISSION";
             rs = stmt.executeQuery(sql);
             rs.first();
             textIDD.setText(rs.getString(1));
                textName.setText(rs.getString(2));
                textF_Name.setText(rs.getString(3));
                textEMAIL.setText(rs.getString(4));
                textTelephone.setText(rs.getString(5));
                textCELL_NO.setText(rs.getString(6));
                textAddress.setText(rs.getString(7));
                textclass.setText(rs.getString(8));
                textCountry.setText(rs.getString(9));
                textCITY.setText(rs.getString(10));
                textdateofbirth.setText(rs.getString(11));
                textOCCUPATION.setText(rs.getString(12));
                textgender.setText(rs.getString(15));
                
                byte[] img = rs.getBytes(14);
                ImageIcon ii = new ImageIcon(img);
                jLabel2.setIcon(ii);
                textAmount.setText(rs.getString(16));
         } catch (SQLException ex) {
             error.Error er = new error.Error();
             er.displayPane("Start NeatBeans Server");
             
         }finally{
            try {
                rs.close();pr.close();
            } catch (Exception e) {
            }
        }
    
    }
    
    //this method id get id from databse and set id when program is running
    public void id(){
         try {
             rs.last();
             String id = rs.getString("ID");
             textIDD.setText(id);
         } catch (SQLException ex) {
           
         }finally{
        try{ rs.close(); pr.close();}
        catch(Exception e){
         }
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textID = new javax.swing.JLabel();
        textNAME = new javax.swing.JLabel();
        text_Fname = new javax.swing.JLabel();
        textEmail = new javax.swing.JLabel();
        textNum = new javax.swing.JLabel();
        textNum1 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textF_Name = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        textTelephone = new javax.swing.JTextField();
        textEMAIL = new javax.swing.JTextField();
        textNum2 = new javax.swing.JLabel();
        textNum3 = new javax.swing.JLabel();
        textCountry = new javax.swing.JTextField();
        textNum4 = new javax.swing.JLabel();
        textCITY = new javax.swing.JTextField();
        textNum5 = new javax.swing.JLabel();
        textNum6 = new javax.swing.JLabel();
        textOCCUPATION = new javax.swing.JTextField();
        textNum7 = new javax.swing.JLabel();
        textCELL_NO = new javax.swing.JTextField();
        textIDD = new javax.swing.JLabel();
        textNum8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textAmount = new javax.swing.JTextField();
        textNum9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        textclass = new javax.swing.JLabel();
        textdateofbirth = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        textID1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        textgender = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jmini = new javax.swing.JLabel();
        jclose = new javax.swing.JLabel();
        framedrag = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admission Form");
        setLocation(new java.awt.Point(250, 50));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        textID.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(204, 0, 51));
        textID.setText("ID");

        textNAME.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNAME.setText("Name:");

        text_Fname.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        text_Fname.setText("Father Name:");

        textEmail.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textEmail.setText("Email:");

        textNum.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum.setText("Cell No#");

        textNum1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum1.setText("Address:");

        textName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textName.setName("Name");
        textName.setSelectionColor(new java.awt.Color(0, 204, 255));
        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        textF_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textF_Name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textF_Name.setName("Name");
        textF_Name.setSelectionColor(new java.awt.Color(0, 204, 255));
        textF_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_NameActionPerformed(evt);
            }
        });

        textAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textAddress.setName("Name");
        textAddress.setSelectionColor(new java.awt.Color(0, 204, 255));
        textAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddressActionPerformed(evt);
            }
        });
        textAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAddressKeyTyped(evt);
            }
        });

        textTelephone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textTelephone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textTelephone.setName("Name");
        textTelephone.setSelectionColor(new java.awt.Color(0, 204, 255));
        textTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelephoneActionPerformed(evt);
            }
        });
        textTelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelephoneKeyTyped(evt);
            }
        });

        textEMAIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textEMAIL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textEMAIL.setName("Name");
        textEMAIL.setSelectionColor(new java.awt.Color(0, 204, 255));
        textEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEMAILActionPerformed(evt);
            }
        });

        textNum2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum2.setText("Class:");

        textNum3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum3.setText("Country:");

        textCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCountry.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCountry.setName("Name");
        textCountry.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCountryActionPerformed(evt);
            }
        });
        textCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCountryKeyTyped(evt);
            }
        });

        textNum4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum4.setText("City");

        textCITY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCITY.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCITY.setName("Name");
        textCITY.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCITYActionPerformed(evt);
            }
        });
        textCITY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCITYKeyTyped(evt);
            }
        });

        textNum5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum5.setText("Date of Birth:");

        textNum6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum6.setText("Occupation:");

        textOCCUPATION.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textOCCUPATION.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textOCCUPATION.setName("Name");
        textOCCUPATION.setSelectionColor(new java.awt.Color(0, 204, 255));
        textOCCUPATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textOCCUPATIONActionPerformed(evt);
            }
        });
        textOCCUPATION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textOCCUPATIONKeyTyped(evt);
            }
        });

        textNum7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum7.setText("Tel No#");

        textCELL_NO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCELL_NO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCELL_NO.setName("Name");
        textCELL_NO.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCELL_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCELL_NOActionPerformed(evt);
            }
        });
        textCELL_NO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCELL_NOKeyTyped(evt);
            }
        });

        textIDD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textIDD.setForeground(new java.awt.Color(204, 0, 0));
        textIDD.setText("1");

        textNum8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum8.setText("Gender:");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/webcam.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/Upload to the Cloud.png"))); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textAmount.setName("Name");
        textAmount.setSelectionColor(new java.awt.Color(0, 204, 255));
        textAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAmountActionPerformed(evt);
            }
        });
        textAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAmountKeyTyped(evt);
            }
        });

        textNum9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum9.setText("Admission Amount");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/User_24x24.png"))); // NOI18N
        jButton4.setText("First");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/Upload_24x24.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/closeclick.png"))); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        textclass.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textclass.setText("Class:");

        textdateofbirth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textdateofbirth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textdateofbirth.setName("Name");
        textdateofbirth.setSelectionColor(new java.awt.Color(0, 204, 255));
        textdateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdateofbirthActionPerformed(evt);
            }
        });
        textdateofbirth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textdateofbirthKeyTyped(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/User_24x24.png"))); // NOI18N
        jButton7.setText("Last");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        textID1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textID1.setForeground(new java.awt.Color(204, 0, 51));
        textID1.setText("By ID:");

        txtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtid.setAlignmentX(1.5F);
        txtid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        txtid.setName("Name");
        txtid.setSelectionColor(new java.awt.Color(0, 204, 255));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        textgender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textgender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textgender.setName("Name");
        textgender.setSelectionColor(new java.awt.Color(0, 204, 255));
        textgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textgenderActionPerformed(evt);
            }
        });
        textgender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textgenderKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(textNum8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textgender, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(textNum5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textID)
                                        .addComponent(textNAME)
                                        .addComponent(text_Fname)
                                        .addComponent(textEmail))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textIDD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textNum1)
                                        .addComponent(textNum7)
                                        .addComponent(textNum2))
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(textNum)
                                            .addGap(18, 18, 18)
                                            .addComponent(textCELL_NO))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(textclass)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textNum6)
                                                .addComponent(textNum3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(textCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(36, 36, 36)
                                                    .addComponent(textNum4)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(textCITY, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(textOCCUPATION, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(textNum9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(textAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textID1)
                                .addGap(18, 18, 18)
                                .addComponent(txtid))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textID)
                                    .addComponent(textIDD))
                                .addGap(18, 18, 18)
                                .addComponent(textNAME)
                                .addGap(18, 18, 18)
                                .addComponent(text_Fname))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmail)
                            .addComponent(textEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(textNum7))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNum)
                        .addComponent(textCELL_NO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNum1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum2)
                    .addComponent(textNum3)
                    .addComponent(textCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNum4)
                    .addComponent(textCITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textclass))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum5)
                    .addComponent(textNum6)
                    .addComponent(textOCCUPATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNum9)
                    .addComponent(textAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum8)
                    .addComponent(textgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textID1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("MODIFY");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/school3.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Karachi Secondary School");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel8)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 750, 610));

        jLabel23.setFont(new java.awt.Font("Traditional Arabic", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("+256704277679");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Contact#");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, -1, -1));

        jLabel21.setFont(new java.awt.Font("Traditional Arabic", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CoreTechTechnologies");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 655, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Develop By");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 655, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/bnewadd.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 755, -1));

        jmini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/mini.png"))); // NOI18N
        jmini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jminiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jminiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jminiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jminiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jminiMouseReleased(evt);
            }
        });
        getContentPane().add(jmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 6, 24, 26));

        jclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/close.png"))); // NOI18N
        jclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcloseMouseReleased(evt);
            }
        });
        getContentPane().add(jclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 6, 26, 26));

        framedrag.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        framedrag.setForeground(new java.awt.Color(255, 255, 255));
        framedrag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        framedrag.setText("<html> <span style=\"text-shadow: 0 1px 0 #ccc,                0 2px 0 #c9c9c9,                0 3px 0 #bbb,                0 4px 0 #b9b9b9,                0 5px 0 #aaa,                0 6px 1px rgba(0,0,0,.1),                0 0 5px rgba(0,0,0,.1),                0 1px 3px rgba(0,0,0,.3),                0 3px 5px rgba(0,0,0,.2),                0 5px 10px rgba(0,0,0,.25),                0 10px 10px rgba(0,0,0,.2),                0 20px 20px rgba(0,0,0,.15); box-shadow:red 2px 2px \"> Modify Admission Form</span> <html>");
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        getContentPane().add(framedrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 22));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/tnewadd.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 35));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/bc.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 676));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseClicked
        // this is use for minimize
        this.setState(update.ICONIFIED);

    }//GEN-LAST:event_jminiMouseClicked

    private void jminiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseEntered
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/minihover.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseEntered

    private void jminiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseExited
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/mini.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseExited

    private void jminiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMousePressed
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/miniclick.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMousePressed

    private void jminiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseReleased
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/minihover.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseReleased

    private void jcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseClicked
        // close jframe
        this.dispose();

    }//GEN-LAST:event_jcloseMouseClicked

    private void jcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseEntered
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closehover.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseEntered

    private void jcloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseExited
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/close.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseExited

    private void jcloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMousePressed
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closeclick.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMousePressed

    private void jcloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseReleased
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closehover.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseReleased

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        //set screen
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y - yMouse);

    }//GEN-LAST:event_framedragMouseDragged

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
        //set mouse pressed screen
        xMouse  = evt.getX();
        yMouse  = evt.getY();
    }//GEN-LAST:event_framedragMousePressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try{//get next data
            //create statment query
            String sql = "Select * from MOIN.ADMISSION";
            rs = stmt.executeQuery(sql);
            if(rs.last()){
                textIDD.setText(Integer.toString(rs.getInt(1)));
                textName.setText(rs.getString(2));
                textF_Name.setText(rs.getString(3));
                textEMAIL.setText(rs.getString(4));
                textTelephone.setText(rs.getString(5));
                textCELL_NO.setText(rs.getString(6));
                textAddress.setText(rs.getString(7));
                textclass.setText(rs.getString(8));
                textCountry.setText(rs.getString(9));
                textCITY.setText(rs.getString(10));
                textdateofbirth.setText(rs.getString(11));
                textOCCUPATION.setText(rs.getString(12));
                byte[] img = rs.getBytes(14);
                ImageIcon ii = new ImageIcon(img);
                jLabel2.setIcon(ii);
                textAmount.setText(rs.getString(16));
                textgender.setText(rs.getString(15));

            }
            else {
                
                error.Error er = new error.Error();
             er.displayPane("End of Faculty");
                ;
            }
        }
        catch(Exception e){
        }
        finally{
            try {
               // rs.close();pr.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void textdateofbirthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textdateofbirthKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textdateofbirthKeyTyped

    private void textdateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdateofbirthActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
           if(txtid.getText() !=null || !"".equals(txtid.getText())){
            //get id from textfield and delete row 
            int id = Integer.parseInt(txtid.getText());
            String sq = "DELETE from MOIN.ADMISSION where ID ="+id;
            pr = con.prepareStatement(sq);
           pr.execute();
            MessagePane ms = new MessagePane();
                ms.displayPane("Delete Succesfully");
           }
           else{
           error.Error er = new error.Error();
             er.displayPane("ID "+txtid.getText()+"Doesn't Exit");
                
           }
        } catch(Exception e){
             error.Error er = new error.Error();
             er.displayPane("ID "+txtid.getText()+"Doesn't Exit");
        }
        finally{
            try {
                rs.close();pr.close();
            } catch (Exception e) {
            }
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String sq = "DELETE from MOIN.ADMISSIOn where ID ="+textIDD.getText();
            pr = con.prepareStatement(sq);
           pr.execute();
          
            String value1 = textName.getText();
            String value2 = textF_Name.getText();
             String value3 = textEMAIL.getText();
            String value4 = textTelephone.getText();
             String value5 = textCELL_NO.getText();
            String value6 = textAddress.getText();
             String value7 = textCountry.getText();
            String value8 = textCITY.getText();
             String value9 = textdateofbirth.getText();
            String value10 = textOCCUPATION.getText();
            String value11 = textAmount.getText();
             byte[] value12 = perImg;
            int value13 = Integer.parseInt(textIDD.getText());
            String value14 = textgender.getText();
            
                //create query for prepareStatement for insert data into database
                String sqq = "insert into MOIN.ADMISSION (ID,NAME,F_NAME,EMAIL,TELEPHONE,CELL_NO,ADDRESS,CLASS,COUNTRY,CITY,DATE_OF_BIRTH,OCCUPATION,ADDMISSION_DATE,PHOTO,GENDER,AMOUNT) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                pr = con.prepareStatement(sqq);
               pr.setInt(1,value13);
                pr.setString(2, value1);
                pr.setString(3, value2);
                pr.setString(4, value3);
                pr.setString(5, value4);
                pr.setString(6, value5);
                pr.setString(7, value6);
                pr.setString(8, textclass.getText());
                pr.setString(9, value7);
                pr.setString(10, value8);
                pr.setString(11, value9);
                pr.setString(12, value10);
                pr.setDate(13,Date.valueOf(LocalDate.now()));
                pr.setBytes(14, perImg);
                pr.setString(15, value14);
                pr.setString(16, value11);
                pr.execute();
         /*   String sql = "UPDATE ADMISSION set  name='"+value1+"', f_name='"+value2+"' ,  email='"+value3+"', TELEPHONE='"+value4+"' ,  CELL_NO='"+value5+"', ADDRESS='"+value6+"' ,  COUNTRY='"+value7+"', CITY='"+value8+"' ,  DATE_OF_BIRTH='"+value9+"', OCCUPATION='"+value10+"' ,  Amount='"+value11+"', Gender='"+rd+"' ,   PHOTO='"+value12+"' WHERE id='"+value13+"'";
                pr = con.prepareStatement(sql);
                pr.execute();*/
                MessagePane ms = new MessagePane();
                ms.displayPane("Succussfully Update");
                this.dispose();
        }catch(Exception e){
           javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
        finally{
            try {
                rs.close();pr.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{//get next data
            //create statment query
            String sql = "Select * from MOIN.ADMISSION";
            rs = stmt.executeQuery(sql);
            rs.first();
                textIDD.setText(rs.getString(1));
                textName.setText(rs.getString(2));
                textF_Name.setText(rs.getString(3));
                textEMAIL.setText(rs.getString(4));
                textTelephone.setText(rs.getString(5));
                textCELL_NO.setText(rs.getString(6));
                textAddress.setText(rs.getString(7));
                textclass.setText(rs.getString(8));
                textCountry.setText(rs.getString(9));
                textCITY.setText(rs.getString(10));
                textdateofbirth.setText(rs.getString(11));
                textOCCUPATION.setText(rs.getString(12));
                byte[] img = rs.getBytes(14);
                ImageIcon ii = new ImageIcon(img);
                jLabel2.setIcon(ii);
                textAmount.setText(rs.getString(16));

           
        }
        catch(Exception e){
        }
        finally{
            try {
                rs.close();pr.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void textAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAmountKeyTyped
        //i am using char datatype for get getkeychar from textfield and creating an if statement
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textAmountKeyTyped

    private void textAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser  chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        file_name = f.getAbsolutePath();
        try {
            File img = new File(file_name);
            FileInputStream file = new FileInputStream(img);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for(int read; (read=file.read(buf))!=-1;){
                bos.write(buf,0,read);

            }
            perImg = bos.toByteArray();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(update.class.getName()).log(Level.SEVERE, null, ex);
        }
        byte[] bt = perImg;
        ImageIcon ii = new ImageIcon(bt);
        jLabel2.setIcon(ii);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textCELL_NOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCELL_NOKeyTyped
        //i am using char datatype for get getkeychar from textfield and creating an if statement
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textCELL_NOKeyTyped

    private void textCELL_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCELL_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCELL_NOActionPerformed

    private void textOCCUPATIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textOCCUPATIONKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textOCCUPATIONKeyTyped

    private void textOCCUPATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textOCCUPATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textOCCUPATIONActionPerformed

    private void textCITYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCITYKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textCITYKeyTyped

    private void textCITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCITYActionPerformed

    private void textCountryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCountryKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textCountryKeyTyped

    private void textCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCountryActionPerformed

    private void textEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEMAILActionPerformed

    private void textTelephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelephoneKeyTyped
        //i am using char datatype for get getkeychar from textfield and creating an if statement
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textTelephoneKeyTyped

    private void textTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTelephoneActionPerformed

    }//GEN-LAST:event_textTelephoneActionPerformed

    private void textAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressKeyTyped

    private void textAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressActionPerformed

    private void textF_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textF_NameActionPerformed

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyTyped

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
       try{ //this query search data from database
            String sql = "Select * from ADMISSION where ID=?";
            pr = con.prepareStatement(sql);
            pr.setString(1,txtid.getText());
            rs = pr.executeQuery();
            if(rs.next()){
                textIDD.setText(rs.getString(1));
                textName.setText(rs.getString(2));
                textF_Name.setText(rs.getString(3));
                textEMAIL.setText(rs.getString(4));
                textTelephone.setText(rs.getString(5));
                textCELL_NO.setText(rs.getString(6));
                textAddress.setText(rs.getString(7));
                textclass.setText(rs.getString(8));
                textCountry.setText(rs.getString(9));
                textCITY.setText(rs.getString(10));
                textdateofbirth.setText(rs.getString(11));
                textOCCUPATION.setText(rs.getString(12));
                byte[] img = rs.getBytes(14);
                ImageIcon ii = new ImageIcon(img);
                jLabel2.setIcon(ii);
                textAmount.setText(rs.getString(16));
                textgender.setText(rs.getString(15));
            } }
       
        catch(Exception e){
        }
        finally{
            try {
                rs.close();pr.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_txtidKeyReleased

    private void textgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textgenderActionPerformed

    private void textgenderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textgenderKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textgenderKeyTyped
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel framedrag;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jclose;
    private javax.swing.JLabel jmini;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textAmount;
    private javax.swing.JTextField textCELL_NO;
    private javax.swing.JTextField textCITY;
    private javax.swing.JTextField textCountry;
    private javax.swing.JTextField textEMAIL;
    private javax.swing.JLabel textEmail;
    private javax.swing.JTextField textF_Name;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textID1;
    private javax.swing.JLabel textIDD;
    private javax.swing.JLabel textNAME;
    private javax.swing.JTextField textName;
    private javax.swing.JLabel textNum;
    private javax.swing.JLabel textNum1;
    private javax.swing.JLabel textNum2;
    private javax.swing.JLabel textNum3;
    private javax.swing.JLabel textNum4;
    private javax.swing.JLabel textNum5;
    private javax.swing.JLabel textNum6;
    private javax.swing.JLabel textNum7;
    private javax.swing.JLabel textNum8;
    private javax.swing.JLabel textNum9;
    private javax.swing.JTextField textOCCUPATION;
    private javax.swing.JTextField textTelephone;
    private javax.swing.JLabel text_Fname;
    private javax.swing.JLabel textclass;
    private javax.swing.JTextField textdateofbirth;
    private javax.swing.JTextField textgender;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

//this globale variable or instance variable
String file_name = null;
private  ImageIcon format  = null;
int s = 0;
byte[] perImg = null;

   
}
