/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Faculty;

import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import message.MessagePane;

/**
 *
 * @author Engr.Awais
 */
public final class NewFaculty extends javax.swing.JFrame {

    /**
     * Creates new form NewFaculty
     */
    public NewFaculty() {
        initComponents();
        this.setLocationRelativeTo(null);
        radio();
        connect();
    }
    
    
    //create instance variable
     Connection con;
     Statement stmt;
     ResultSet rs;
     PreparedStatement pr;
    //instance variable for mouse drag
     int xMouse;
     int yMouse;
     
     //get only one radio button text
     public void radio(){
         //create group of radio button
     ButtonGroup bn = new ButtonGroup();
     bn.add(jRadioButton1);
     bn.add(jRadioButton2);
    }
     //get connection from database
     public void connect(){
        String uHost="jdbc:derby://localhost:1527/School Management";
        String uName="moin";
        String uPass="akhtar";
         try {
             //connectivity from database
             con = DriverManager.getConnection(uHost, uName, uPass);
             stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
             //get data from database
             String sql = "Select * from MOIN.FACULTY";
             rs = stmt.executeQuery(sql);
             rs.last();
             String id = rs.getString("ID");
             jLabel4.setText(id);
            
         } catch (SQLException ex) {
             error.Error er = new error.Error();
             er.displayPane("Start NeatBeans Server");
         }finally{
        try{rs.close(); pr.close();}
        catch(Exception e){
           
         }
        }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textName = new javax.swing.JTextField();
        textNAME = new javax.swing.JLabel();
        text_Fname = new javax.swing.JLabel();
        textF_Name = new javax.swing.JTextField();
        textEmail = new javax.swing.JLabel();
        textEMAIL = new javax.swing.JTextField();
        textNum = new javax.swing.JLabel();
        textCELL_NO = new javax.swing.JTextField();
        textCITY = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        textNum8 = new javax.swing.JLabel();
        textNum4 = new javax.swing.JLabel();
        textNum5 = new javax.swing.JLabel();
        textNum6 = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        textsalary = new javax.swing.JTextField();
        textNic = new javax.swing.JTextField();
        textNum1 = new javax.swing.JLabel();
        textNum2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        textNum9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        textNum3 = new javax.swing.JLabel();
        jComboYear = new javax.swing.JComboBox<>();
        jComboMonth = new javax.swing.JComboBox<>();
        jComboDate2 = new javax.swing.JComboBox<>();
        textNum12 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNum10 = new javax.swing.JLabel();
        textNum11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jmini = new javax.swing.JLabel();
        jclose = new javax.swing.JLabel();
        framedrag = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Faculty");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/login/img/icon.png")));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(810, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("NEW FACULTY");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/school3.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("Karachi Secondary School");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel8)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        textName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textName.setName("Name");
        textName.setSelectionColor(new java.awt.Color(0, 204, 255));
        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        textNAME.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNAME.setText("Name:");

        text_Fname.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        text_Fname.setText("Father Name:");

        textF_Name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textF_Name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textF_Name.setName("Name");
        textF_Name.setSelectionColor(new java.awt.Color(0, 204, 255));
        textF_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textF_NameActionPerformed(evt);
            }
        });

        textEmail.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textEmail.setText("Email:");

        textEMAIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textEMAIL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textEMAIL.setName("Name");
        textEMAIL.setSelectionColor(new java.awt.Color(0, 204, 255));
        textEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEMAILActionPerformed(evt);
            }
        });

        textNum.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum.setText("Cell No#");

        textCELL_NO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCELL_NO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCELL_NO.setName("Name");
        textCELL_NO.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCELL_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCELL_NOActionPerformed(evt);
            }
        });
        textCELL_NO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCELL_NOKeyTyped(evt);
            }
        });

        textCITY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCITY.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textCITY.setName("Name");
        textCITY.setSelectionColor(new java.awt.Color(0, 204, 255));
        textCITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCITYActionPerformed(evt);
            }
        });
        textCITY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textCITYKeyTyped(evt);
            }
        });

        jRadioButton2.setText("Female");

        jRadioButton1.setText("Male");

        textNum8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum8.setText("Gender:");

        textNum4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum4.setText("City:");

        textNum5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum5.setText("Salary:");

        textNum6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum6.setText("Address:");

        textAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textAddress.setName("Name");
        textAddress.setSelectionColor(new java.awt.Color(0, 204, 255));
        textAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAddressActionPerformed(evt);
            }
        });
        textAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAddressKeyTyped(evt);
            }
        });

        textsalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textsalary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textsalary.setName("Name");
        textsalary.setSelectionColor(new java.awt.Color(0, 204, 255));
        textsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsalaryActionPerformed(evt);
            }
        });
        textsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textsalaryKeyTyped(evt);
            }
        });

        textNic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textNic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textNic.setName("Name");
        textNic.setSelectionColor(new java.awt.Color(0, 204, 255));
        textNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNicActionPerformed(evt);
            }
        });
        textNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNicKeyTyped(evt);
            }
        });

        textNum1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum1.setText("CNIC#");

        textNum2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum2.setText("Qualification:");

        jComboBox1.setBackground(new java.awt.Color(0, 0, 255));
        jComboBox1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matric", "Intermediate", "Bechelor", "Master", "Ms/M.phil" }));

        textNum9.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        textNum9.setForeground(new java.awt.Color(0, 153, 153));
        textNum9.setText("Which Subject can you teach?");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(15);
        jTextArea1.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox1.setText("English");

        jCheckBox2.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox2.setText("Urdu");

        jCheckBox3.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox3.setText("Islamiat");

        jCheckBox4.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox4.setText("P.st");

        jCheckBox5.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox5.setText("Physics");

        jCheckBox6.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox6.setText("Sindhi");

        jCheckBox7.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox7.setText("Computer");

        jCheckBox8.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox8.setText("Math");

        jCheckBox9.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox9.setText("Science");

        jCheckBox10.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jCheckBox10.setText("Chemistry");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/Stock Index Up_24x24.png"))); // NOI18N
        jButton2.setText("Get Selected Subject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textNum3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum3.setText("Joining Date");

        jComboYear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboYear.setForeground(new java.awt.Color(255, 0, 51));
        jComboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2015", "2016", "2017", "2018" }));

        jComboMonth.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboMonth.setForeground(new java.awt.Color(255, 0, 51));
        jComboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUG", "SEPT", "OCT", "NOV", "DEC" }));

        jComboDate2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboDate2.setForeground(new java.awt.Color(255, 0, 51));
        jComboDate2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboDate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDate2ActionPerformed(evt);
            }
        });

        textNum12.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum12.setText("Teacher ID");

        textID.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        textID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textIDKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Last Entered ID");

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("jLabel4");

        jCheckBox11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox11.setText("I Accept all Term & Condition");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNum12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(textNum9)
                                .addGap(141, 141, 141))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox9)
                                    .addComponent(jCheckBox10))
                                .addGap(25, 25, 25))
                            .addComponent(jScrollPane1)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textNum6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(textNum1)
                                        .addGap(18, 18, 18)
                                        .addComponent(textNic))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textNAME)
                                            .addComponent(textNum4)
                                            .addComponent(textEmail))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textEMAIL, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textCITY)
                                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_Fname)
                                            .addComponent(textNum)
                                            .addComponent(textNum5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textCELL_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(textNum2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textNum8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textNum3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum12)
                    .addComponent(textID)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textNAME)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textEmail)
                            .addComponent(textEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_Fname)
                            .addComponent(textF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNum)
                            .addComponent(textCELL_NO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum4)
                    .addComponent(textCITY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNum5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum1)
                    .addComponent(textNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNum2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNum6)
                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNum8)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNum9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox2)
                                .addComponent(jCheckBox9))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox5)
                                .addComponent(jCheckBox7))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNum3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox11)
                .addGap(11, 11, 11))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setToolTipText("");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/webcam.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        textNum10.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        textNum10.setForeground(new java.awt.Color(255, 0, 0));
        textNum10.setText("Note.............!");

        textNum11.setBackground(new java.awt.Color(255, 255, 255));
        textNum11.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        textNum11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/note.png"))); // NOI18N
        textNum11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/Upload to the Cloud.png"))); // NOI18N
        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNum10)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textNum11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNum10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNum11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/Print_24x24.png"))); // NOI18N
        jButton3.setText("Print Oppointment Letter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(92, 92, 92))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 640));

        jmini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/mini.png"))); // NOI18N
        jmini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jminiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jminiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jminiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jminiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jminiMouseReleased(evt);
            }
        });
        getContentPane().add(jmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 5, 24, 26));

        jclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/close.png"))); // NOI18N
        jclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcloseMouseReleased(evt);
            }
        });
        getContentPane().add(jclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 5, 26, 26));

        framedrag.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        framedrag.setForeground(new java.awt.Color(255, 255, 255));
        framedrag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        framedrag.setText("<html>\n<span style=\"text-shadow: 0 1px 0 #ccc,\n               0 2px 0 #c9c9c9,\n               0 3px 0 #bbb,\n               0 4px 0 #b9b9b9,\n               0 5px 0 #aaa,\n               0 6px 1px rgba(0,0,0,.1),\n               0 0 5px rgba(0,0,0,.1),\n               0 1px 3px rgba(0,0,0,.3),\n               0 3px 5px rgba(0,0,0,.2),\n               0 5px 10px rgba(0,0,0,.25),\n               0 10px 10px rgba(0,0,0,.2),\n               0 20px 20px rgba(0,0,0,.15); box-shadow:red 2px 2px \">\nNew Faculty\n</span>\n<html>");
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        getContentPane().add(framedrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 23));

        jLabel23.setFont(new java.awt.Font("Traditional Arabic", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("03412281694");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Contact#");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, -1, -1));

        jLabel21.setFont(new java.awt.Font("Traditional Arabic", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Moin Akhtar");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("Develop By");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/t7.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/b7.png"))); // NOI18N
        jLabel9.setText("j");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 810, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/img/menu/bc7.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void textF_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textF_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textF_NameActionPerformed

    private void textEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEMAILActionPerformed

    private void textCELL_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCELL_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCELL_NOActionPerformed

    private void textCELL_NOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCELL_NOKeyTyped
        //using char data type for get keychar
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textCELL_NOKeyTyped

    private void textCITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCITYActionPerformed

    private void textCITYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCITYKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textCITYKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //create object for get file path and get file like image
        JFileChooser  chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        file_name = f.getAbsolutePath();
        try {
            File img = new File(file_name);
            FileInputStream file = new FileInputStream(img);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int read; (read=file.read(buf))!=-1;){
            bos.write(buf,0,read);
            }
            perImg = bos.toByteArray();
        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
        }
        byte[] bt = perImg;
        ImageIcon ii = new ImageIcon(bt);
        jLabel2.setIcon(ii);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void textAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressActionPerformed

    private void textAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textAddressKeyTyped

    private void textsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsalaryActionPerformed

    private void textsalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textsalaryKeyTyped
         //using char data type for get keychar 
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_textsalaryKeyTyped

    private void textNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNicActionPerformed

    private void textNicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNicKeyTyped
         //using char data type for get keychar
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textNicKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //get check box text
        String s = "";
        if(jCheckBox1.isSelected()){
        s = s + " " + jCheckBox1.getText() + ", ";
        }
        if(jCheckBox2.isSelected()){
        s = s + " " + jCheckBox2.getText() + ", ";
        }
        if(jCheckBox3.isSelected()){
        s = s + " " + jCheckBox3.getText() + ", ";
        }
        if(jCheckBox4.isSelected()){
        s = s + " " + jCheckBox4.getText() + ", ";
        }
        if(jCheckBox5.isSelected()){
        s = s + " " + jCheckBox5.getText() + ", ";
        }
        if(jCheckBox6.isSelected()){
        s = s + " " + jCheckBox6.getText() + ", ";
        }
        if(jCheckBox7.isSelected()){
        s = s + " " + jCheckBox7.getText() + ",";
        }
        if(jCheckBox8.isSelected()){
        s = s + " " + jCheckBox8.getText() + ", ";
        }
        if(jCheckBox9.isSelected()){
        s = s + " " + jCheckBox9.getText() + ", ";
        }
        if(jCheckBox10.isSelected()){
        s = s + " " + jCheckBox10.getText() + ", ";
        }
         jTextArea1.setText(s);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboDate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboDate2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            //if statement create for gettext from fields and set in database
        if(jCheckBox11.isSelected() && (format != null || perImg != null  )){
            String id = textID.getText();
            String name = textName.getText();
            String f_Name = textF_Name.getText();
            String email = textEMAIL.getText();
            String cell = textCELL_NO.getText();
            String address = textAddress.getText();
            String city = textCITY.getText();
            String JoinDate = (String) jComboDate2.getSelectedItem()+"/"+ jComboMonth.getSelectedItem() +"/"+ jComboYear.getSelectedItem();
            String cnic = textNic.getText();
            String salary = textsalary.getText();
            String subject = jTextArea1.getText();
            String qualification = (String) jComboBox1.getSelectedItem();
            String gender = "";
            //get radio button value
            if(jRadioButton1.isSelected()){
                gender = jRadioButton1.getText();
            }
            else if(jRadioButton2.isSelected()){
                gender = jRadioButton2.getText();
            }
            try {
                //insert data into database
                String sqq = "insert into MOIN.FACULTY (NAME,F_NAME,EMAIL,CITY,SALARY,CNIC,QUALIFICATION,ADDRESS,GENDER,SUBJECT,PICTURE,RESIGN_DATE,CELL_NO,JOINING_DATE,ID) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                pr = con.prepareStatement(sqq);
                pr.setString(1, name);
                pr.setString(2, f_Name);
                pr.setString(3, email);
                pr.setString(4, city);
                pr.setString(5, salary);
                pr.setString(6,cnic);
                pr.setString(7, qualification);
                pr.setString(8, address);
                pr.setString(9, gender);
                pr.setString(10, subject);
                pr.setBytes(11,perImg);
                pr.setString(12, "NULL");
                pr.setString(13, cell);
                pr.setString(14, JoinDate);
                pr.setInt(15, Integer.parseInt(id));
                pr.execute();
                pr.close();
                rs.close();
                //insert data into database of salary
                String sqqq = "insert into MOIN.SALARY (ID,NAME,SALARY) values(?,?,?)";
                pr = con.prepareStatement(sqqq);
                pr.setInt(1, Integer.parseInt(id));
                pr.setString(2,name);
                pr.setInt(3, Integer.parseInt(salary));
                pr.execute();
                rs.close();
                MessagePane ms = new MessagePane();
                ms.displayPane("Successfully Faculty Added");
                oppointment op = new oppointment();
                this.dispose();
                op.setVisible(true);
                this.disable();
            } catch (SQLException | HeadlessException ex) {
                error.Error er = new error.Error();
                 er.displayPane("<html><font size=\"1.5\">use unique ID or CNIC or CELL#</font></html>");

            }finally{
        try{rs.close(); pr.close();}
        catch(Exception e){
           
         }
        }

        }
        else{
            error.Error er = new error.Error();
            er.displayPane("<html><font size=\"1.5\">Please Accept term & Condition OR Upload Photo</font></html>");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIDKeyReleased
        
    }//GEN-LAST:event_textIDKeyReleased

    private void textIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textIDKeyTyped
         //using char data type for get keychar 
        char num=evt.getKeyChar();
        if(!(Character.isDigit(num)|| (num==KeyEvent.VK_BACKSPACE) || num==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textIDKeyTyped

    private void jminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseClicked
        // this is use for minimize
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jminiMouseClicked

    private void jminiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseEntered
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/minihover.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseEntered

    private void jminiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseExited
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/mini.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseExited

    private void jminiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMousePressed
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/miniclick.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMousePressed

    private void jminiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminiMouseReleased
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/minihover.png"));
        jmini.setIcon(ii);
    }//GEN-LAST:event_jminiMouseReleased

    private void jcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseClicked
        // close jframe
        this.dispose();
    }//GEN-LAST:event_jcloseMouseClicked

    private void jcloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseEntered
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closehover.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseEntered

    private void jcloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseExited
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/close.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseExited

    private void jcloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMousePressed
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closeclick.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMousePressed

    private void jcloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseReleased
        //set image in label
        ImageIcon ii = new ImageIcon(getClass().getResource("/login/img/closehover.png"));
        jclose.setIcon(ii);
    }//GEN-LAST:event_jcloseMouseReleased

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        //set screen
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y - yMouse);
    }//GEN-LAST:event_framedragMouseDragged

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed
        //set mouse pressed screen
        xMouse  = evt.getX();
        yMouse  = evt.getY();
    }//GEN-LAST:event_framedragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel framedrag;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboDate2;
    private javax.swing.JComboBox<String> jComboMonth;
    private javax.swing.JComboBox<String> jComboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jclose;
    private javax.swing.JLabel jmini;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textCELL_NO;
    private javax.swing.JTextField textCITY;
    private javax.swing.JTextField textEMAIL;
    private javax.swing.JLabel textEmail;
    private javax.swing.JTextField textF_Name;
    private javax.swing.JTextField textID;
    private javax.swing.JLabel textNAME;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNic;
    private javax.swing.JLabel textNum;
    private javax.swing.JLabel textNum1;
    private javax.swing.JLabel textNum10;
    private javax.swing.JLabel textNum11;
    private javax.swing.JLabel textNum12;
    private javax.swing.JLabel textNum2;
    private javax.swing.JLabel textNum3;
    private javax.swing.JLabel textNum4;
    private javax.swing.JLabel textNum5;
    private javax.swing.JLabel textNum6;
    private javax.swing.JLabel textNum8;
    private javax.swing.JLabel textNum9;
    private javax.swing.JLabel text_Fname;
    private javax.swing.JTextField textsalary;
    // End of variables declaration//GEN-END:variables
    //its instance variable for getting image    
    String file_name = null;
     private  ImageIcon format  = null;
     int s = 0;
     byte[] perImg = null;

}
